// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./../src/components/src/modules/code/CodeBlock.vue')['default']
    ColorSelect: typeof import('./../src/components/src/modules/color/ColorSelect.vue')['default']
    CusBubbleMenu: typeof import('./../src/components/src/modules/bubble/CusBubbleMenu.vue')['default']
    CusFloatingMenu: typeof import('./../src/components/src/modules/floating/CusFloatingMenu.vue')['default']
    CusSelet: typeof import('./../src/components/src/modules/components/CusSelet.vue')['default']
    Draw: typeof import('./../src/components/src/modules/draw/Draw.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    Emoji: typeof import('./../src/components/src/modules/emoji/Emoji.vue')['default']
    FontSelect: typeof import('./../src/components/src/modules/font/FontSelect.vue')['default']
    FontStyle: typeof import('./../src/components/src/modules/font/FontStyle.vue')['default']
    IconDropdown: typeof import('./../src/components/src/modules/components/IconDropdown.vue')['default']
    Image: typeof import('./../src/components/src/modules/image/Image.vue')['default']
    ImageDrag: typeof import('./../src/components/src/modules/image/ImageDrag.vue')['default']
    MenuBar: typeof import('./../src/components/src/modules/menu/MenuBar.vue')['default']
    MenuItem: typeof import('./../src/components/src/modules/components/MenuItem.vue')['default']
    TableBubbleMenu: typeof import('./../src/components/src/modules/bubble/TableBubbleMenu.vue')['default']
    Tiptap: typeof import('./../src/components/src/Tiptap.vue')['default']
  }
}
